name: Docker Image CI
on:
  push:
    branches-ignore: master
    tags-ignore: '*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: whoan/docker-build-with-cache-action@v4
        with:
          username: "${{ secrets.DOCKER_USERNAME }}"
          password: "${{ secrets.DOCKER_PASSWORD }}"
          image_name: agandolf/cbioportal-test
          image_tag: latest
          context: ../..
          dockerfile: docker/web-and-data/Dockerfile
          pull_image_and_stages: false
